local LSM = LibStub("LibSharedMedia-3.0") 

-- ----- 
-- BACKGROUND 
-- ----- 

-- ----- 
--  BORDER 
-- ---- 
LSM:Register("border", "Ferous1", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous1.tga]]) 
LSM:Register("border", "Ferous10", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous10.tga]]) 
LSM:Register("border", "Ferous11", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous11.tga]]) 
LSM:Register("border", "Ferous12", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous12.tga]]) 
LSM:Register("border", "Ferous13", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous13.tga]]) 
LSM:Register("border", "Ferous2", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous2.tga]]) 
LSM:Register("border", "Ferous3", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous3.tga]]) 
LSM:Register("border", "Ferous4", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous4.tga]]) 
LSM:Register("border", "Ferous5", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous5.tga]]) 
LSM:Register("border", "Ferous6", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous6.tga]]) 
LSM:Register("border", "Ferous7", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous7.tga]]) 
LSM:Register("border", "Ferous8", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous8.tga]]) 
LSM:Register("border", "Ferous9", [[Interface\Addons\SharedMedia_MyMedia\border\Ferous9.tga]]) 
LSM:Register("border", "RaeliGlow", [[Interface\Addons\SharedMedia_MyMedia\border\RaeliGlow.tga]]) 
LSM:Register("border", "RaeliGlowSmall", [[Interface\Addons\SharedMedia_MyMedia\border\RaeliGlowSmall.tga]]) 
LSM:Register("border", "RothSquare", [[Interface\Addons\SharedMedia_MyMedia\border\RothSquare.tga]]) 
LSM:Register("border", "SeerahScalloped", [[Interface\Addons\SharedMedia_MyMedia\border\SeerahScalloped.blp]]) 

-- -----
--   FONT
-- -----
LSM:Register("font", "ArchivoNarrow-Bold", [[Interface\Addons\SharedMedia_MyMedia\font\ArchivoNarrow-Bold.ttf]]) 
LSM:Register("font", "Arial Narrow Bold", [[Interface\Addons\SharedMedia_MyMedia\font\Arial Narrow Bold.TTF]]) 
LSM:Register("font", "Avant Garde Book BT", [[Interface\Addons\SharedMedia_MyMedia\font\Avant Garde Book BT.ttf]]) 
LSM:Register("font", "Avant Garde Demi BT", [[Interface\Addons\SharedMedia_MyMedia\font\Avant Garde Demi BT.ttf]]) 
LSM:Register("font", "DAMAGE", [[Interface\Addons\SharedMedia_MyMedia\font\DAMAGE.ttf]]) 
LSM:Register("font", "GothamNarrowUltra", [[Interface\Addons\SharedMedia_MyMedia\font\GothamNarrowUltra.ttf]]) 
LSM:Register("font", "JacintoSans", [[Interface\Addons\SharedMedia_MyMedia\font\JacintoSans.ttf]]) 
LSM:Register("font", "Naowh", [[Interface\Addons\SharedMedia_MyMedia\font\Naowh.ttf]]) 
LSM:Register("font", "Prototype", [[Interface\Addons\SharedMedia_MyMedia\font\Prototype.ttf]]) 

-- -----
--   SOUND
-- -----
LSM:Register("sound", "!Beacon", [[Interface\Addons\SharedMedia_MyMedia\sound\!Beacon.mp3]]) 
LSM:Register("sound", "!Big Bang", [[Interface\Addons\SharedMedia_MyMedia\sound\!Big Bang.mp3]]) 
LSM:Register("sound", "!Blistering Cold in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\!Blistering Cold in 5.mp3]]) 
LSM:Register("sound", "!Bloodbeasts in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\!Bloodbeasts in 5.mp3]]) 
LSM:Register("sound", "!Bloodlust", [[Interface\Addons\SharedMedia_MyMedia\sound\!Bloodlust.mp3]]) 
LSM:Register("sound", "!Bone Storm", [[Interface\Addons\SharedMedia_MyMedia\sound\!Bone Storm.mp3]]) 
LSM:Register("sound", "!Cutter in 3", [[Interface\Addons\SharedMedia_MyMedia\sound\!Cutter in 3.mp3]]) 
LSM:Register("sound", "!DBM Beacon", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Beacon.mp3]]) 
LSM:Register("sound", "!DBM Big Bang", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Big Bang.mp3]]) 
LSM:Register("sound", "!DBM Bloodlust over", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Bloodlust over.mp3]]) 
LSM:Register("sound", "!DBM Bloodlust", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Bloodlust.mp3]]) 
LSM:Register("sound", "!DBM Bone Spike", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Bone Spike.mp3]]) 
LSM:Register("sound", "!DBM Bone Storm", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Bone Storm.mp3]]) 
LSM:Register("sound", "!DBM Defensives", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Defensives.mp3]]) 
LSM:Register("sound", "!DBM Disoriented", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Disoriented.mp3]]) 
LSM:Register("sound", "!DBM Dispell", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Dispell.mp3]]) 
LSM:Register("sound", "!DBM Don't Move", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Don't Move.mp3]]) 
LSM:Register("sound", "!DBM DPS Hard", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM DPS Hard.mp3]]) 
LSM:Register("sound", "!DBM DPS More", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM DPS More.mp3]]) 
LSM:Register("sound", "!DBM DPS Slow", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM DPS Slow.mp3]]) 
LSM:Register("sound", "!DBM DPS Stop", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM DPS Stop.mp3]]) 
LSM:Register("sound", "!DBM Empowered Vortex", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Empowered Vortex.mp3]]) 
LSM:Register("sound", "!DBM Enrage", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Enrage.mp3]]) 
LSM:Register("sound", "!DBM Fear", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Fear.mp3]]) 
LSM:Register("sound", "!DBM Flame Orb", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Flame Orb.mp3]]) 
LSM:Register("sound", "!DBM Green", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Green.mp3]]) 
LSM:Register("sound", "!DBM Group", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Group.mp3]]) 
LSM:Register("sound", "!DBM Interrupt", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Interrupt.mp3]]) 
LSM:Register("sound", "!DBM Malleable Goo", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Malleable Goo.mp3]]) 
LSM:Register("sound", "!DBM Mark", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Mark.mp3]]) 
LSM:Register("sound", "!DBM Meteorstrike in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Meteorstrike in 5.mp3]]) 
LSM:Register("sound", "!DBM Mindcontroll", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Mindcontroll.mp3]]) 
LSM:Register("sound", "!DBM Move Left", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Move Left.mp3]]) 
LSM:Register("sound", "!DBM Move Middle", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Move Middle.mp3]]) 
LSM:Register("sound", "!DBM Move Right", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Move Right.mp3]]) 
LSM:Register("sound", "!DBM Necrotic Plague", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Necrotic Plague.mp3]]) 
LSM:Register("sound", "!DBM Red", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Red.mp3]]) 
LSM:Register("sound", "!DBM Run Away", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Run Away.mp3]]) 
LSM:Register("sound", "!DBM Run in", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Run in.mp3]]) 
LSM:Register("sound", "!DBM Run Out", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Run Out.mp3]]) 
LSM:Register("sound", "!DBM Save", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Save.mp3]]) 
LSM:Register("sound", "!DBM Shadow Trap", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Shadow Trap.mp3]]) 
LSM:Register("sound", "!DBM Spirit on you", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Spirit on you.mp3]]) 
LSM:Register("sound", "!DBM Stop Casting", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Stop Casting.mp3]]) 
LSM:Register("sound", "!DBM Stop Cleave", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Stop Cleave.mp3]]) 
LSM:Register("sound", "!DBM Suppressors", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Suppressors.mp3]]) 
LSM:Register("sound", "!DBM Switch Tank", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Switch Tank.mp3]]) 
LSM:Register("sound", "!DBM Switch Target", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Switch Target.mp3]]) 
LSM:Register("sound", "!DBM Unbound Plague", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Unbound Plague.mp3]]) 
LSM:Register("sound", "!DBM Unchained Magic", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Unchained Magic.mp3]]) 
LSM:Register("sound", "!DBM Unchained", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Unchained.mp3]]) 
LSM:Register("sound", "!DBM Valk'yrs", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Valk'yrs.mp3]]) 
LSM:Register("sound", "!DBM Volley Soon", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Volley Soon.mp3]]) 
LSM:Register("sound", "!DBM Watch Stacks", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Watch Stacks.mp3]]) 
LSM:Register("sound", "!DBM Watch your Feet", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM Watch your Feet.mp3]]) 
LSM:Register("sound", "!DBM [C] Blistering Cold in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM [C] Blistering Cold in 5.mp3]]) 
LSM:Register("sound", "!DBM [C] Bloodbeasts in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM [C] Bloodbeasts in 5.mp3]]) 
LSM:Register("sound", "!DBM [C] Cutter in 3", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM [C] Cutter in 3.mp3]]) 
LSM:Register("sound", "!DBM [C] Defile in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM [C] Defile in 5.mp3]]) 
LSM:Register("sound", "!DBM [C] Fear in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM [C] Fear in 5.mp3]]) 
LSM:Register("sound", "!DBM [C] Meteorstrike in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM [C] Meteorstrike in 5.mp3]]) 
LSM:Register("sound", "!DBM [C] Pull in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM [C] Pull in 5.mp3]]) 
LSM:Register("sound", "!DBM [C] Unstable Experiment in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBM [C] Unstable Experiment in 5.mp3]]) 
LSM:Register("sound", "!DBMBone Spike", [[Interface\Addons\SharedMedia_MyMedia\sound\!DBMBone Spike.mp3]]) 
LSM:Register("sound", "!Defensives", [[Interface\Addons\SharedMedia_MyMedia\sound\!Defensives.mp3]]) 
LSM:Register("sound", "!Defile in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\!Defile in 5.mp3]]) 
LSM:Register("sound", "!Disoriented", [[Interface\Addons\SharedMedia_MyMedia\sound\!Disoriented.mp3]]) 
LSM:Register("sound", "!Dispell", [[Interface\Addons\SharedMedia_MyMedia\sound\!Dispell.mp3]]) 
LSM:Register("sound", "!Don't Move", [[Interface\Addons\SharedMedia_MyMedia\sound\!Don't Move.mp3]]) 
LSM:Register("sound", "!Enrage", [[Interface\Addons\SharedMedia_MyMedia\sound\!Enrage.mp3]]) 
LSM:Register("sound", "!Fear in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\!Fear in 5.mp3]]) 
LSM:Register("sound", "!Flame Orb", [[Interface\Addons\SharedMedia_MyMedia\sound\!Flame Orb.mp3]]) 
LSM:Register("sound", "!Green", [[Interface\Addons\SharedMedia_MyMedia\sound\!Green.mp3]]) 
LSM:Register("sound", "!Group", [[Interface\Addons\SharedMedia_MyMedia\sound\!Group.mp3]]) 
LSM:Register("sound", "!Hard DPS", [[Interface\Addons\SharedMedia_MyMedia\sound\!Hard DPS.mp3]]) 
LSM:Register("sound", "!Interrupt", [[Interface\Addons\SharedMedia_MyMedia\sound\!Interrupt.mp3]]) 
LSM:Register("sound", "!Malleable Goo", [[Interface\Addons\SharedMedia_MyMedia\sound\!Malleable Goo.mp3]]) 
LSM:Register("sound", "!More DPS", [[Interface\Addons\SharedMedia_MyMedia\sound\!More DPS.mp3]]) 
LSM:Register("sound", "!Move Left", [[Interface\Addons\SharedMedia_MyMedia\sound\!Move Left.mp3]]) 
LSM:Register("sound", "!Move Middle", [[Interface\Addons\SharedMedia_MyMedia\sound\!Move Middle.mp3]]) 
LSM:Register("sound", "!Move Right", [[Interface\Addons\SharedMedia_MyMedia\sound\!Move Right.mp3]]) 
LSM:Register("sound", "!Paladin Freedom", [[Interface\Addons\SharedMedia_MyMedia\sound\!Paladin Freedom.mp3]]) 
LSM:Register("sound", "!Paladin Protection", [[Interface\Addons\SharedMedia_MyMedia\sound\!Paladin Protection.mp3]]) 
LSM:Register("sound", "!Paladin Sacrifice", [[Interface\Addons\SharedMedia_MyMedia\sound\!Paladin Sacrifice.mp3]]) 
LSM:Register("sound", "!Paladin Salvation", [[Interface\Addons\SharedMedia_MyMedia\sound\!Paladin Salvation.mp3]]) 
LSM:Register("sound", "!Pull in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\!Pull in 5.mp3]]) 
LSM:Register("sound", "!Red", [[Interface\Addons\SharedMedia_MyMedia\sound\!Red.mp3]]) 
LSM:Register("sound", "!Run Away", [[Interface\Addons\SharedMedia_MyMedia\sound\!Run Away.mp3]]) 
LSM:Register("sound", "!Run in", [[Interface\Addons\SharedMedia_MyMedia\sound\!Run in.mp3]]) 
LSM:Register("sound", "!Run Out", [[Interface\Addons\SharedMedia_MyMedia\sound\!Run Out.mp3]]) 
LSM:Register("sound", "!Save", [[Interface\Addons\SharedMedia_MyMedia\sound\!Save.mp3]]) 
LSM:Register("sound", "!Slow DPS", [[Interface\Addons\SharedMedia_MyMedia\sound\!Slow DPS.mp3]]) 
LSM:Register("sound", "!Spell Aggro", [[Interface\Addons\SharedMedia_MyMedia\sound\!Spell Aggro.mp3]]) 
LSM:Register("sound", "!Spell Freedom", [[Interface\Addons\SharedMedia_MyMedia\sound\!Spell Freedom.mp3]]) 
LSM:Register("sound", "!Spell Iron Dwarf", [[Interface\Addons\SharedMedia_MyMedia\sound\!Spell Iron Dwarf.mp3]]) 
LSM:Register("sound", "!Spell PI", [[Interface\Addons\SharedMedia_MyMedia\sound\!Spell PI.mp3]]) 
LSM:Register("sound", "!Spell Protection", [[Interface\Addons\SharedMedia_MyMedia\sound\!Spell Protection.mp3]]) 
LSM:Register("sound", "!Spell PS", [[Interface\Addons\SharedMedia_MyMedia\sound\!Spell PS.mp3]]) 
LSM:Register("sound", "!Spell Sacred shield", [[Interface\Addons\SharedMedia_MyMedia\sound\!Spell Sacred shield.mp3]]) 
LSM:Register("sound", "!Spell Sacrifice", [[Interface\Addons\SharedMedia_MyMedia\sound\!Spell Sacrifice.mp3]]) 
LSM:Register("sound", "!Spell Salvation", [[Interface\Addons\SharedMedia_MyMedia\sound\!Spell Salvation.mp3]]) 
LSM:Register("sound", "!Spell Scale", [[Interface\Addons\SharedMedia_MyMedia\sound\!Spell Scale.mp3]]) 
LSM:Register("sound", "!Spell Spellpower", [[Interface\Addons\SharedMedia_MyMedia\sound\!Spell Spellpower.mp3]]) 
LSM:Register("sound", "!Spell Taunka", [[Interface\Addons\SharedMedia_MyMedia\sound\!Spell Taunka.mp3]]) 
LSM:Register("sound", "!Spell Tricks", [[Interface\Addons\SharedMedia_MyMedia\sound\!Spell Tricks.mp3]]) 
LSM:Register("sound", "!Spell Vrykul", [[Interface\Addons\SharedMedia_MyMedia\sound\!Spell Vrykul.mp3]]) 
LSM:Register("sound", "!Stop Casting", [[Interface\Addons\SharedMedia_MyMedia\sound\!Stop Casting.mp3]]) 
LSM:Register("sound", "!Stop DPS", [[Interface\Addons\SharedMedia_MyMedia\sound\!Stop DPS.mp3]]) 
LSM:Register("sound", "!Suppressors", [[Interface\Addons\SharedMedia_MyMedia\sound\!Suppressors.mp3]]) 
LSM:Register("sound", "!Switch Tank", [[Interface\Addons\SharedMedia_MyMedia\sound\!Switch Tank.mp3]]) 
LSM:Register("sound", "!Switch Target", [[Interface\Addons\SharedMedia_MyMedia\sound\!Switch Target.mp3]]) 
LSM:Register("sound", "!Taunka", [[Interface\Addons\SharedMedia_MyMedia\sound\!Taunka.mp3]]) 
LSM:Register("sound", "!Trinket Iron Dwarf", [[Interface\Addons\SharedMedia_MyMedia\sound\!Trinket Iron Dwarf.mp3]]) 
LSM:Register("sound", "!Trinket Scale", [[Interface\Addons\SharedMedia_MyMedia\sound\!Trinket Scale.mp3]]) 
LSM:Register("sound", "!Trinket Spellpower", [[Interface\Addons\SharedMedia_MyMedia\sound\!Trinket Spellpower.mp3]]) 
LSM:Register("sound", "!Trinket Vrykul", [[Interface\Addons\SharedMedia_MyMedia\sound\!Trinket Vrykul.mp3]]) 
LSM:Register("sound", "!Unchained Magic", [[Interface\Addons\SharedMedia_MyMedia\sound\!Unchained Magic.mp3]]) 
LSM:Register("sound", "!Unstable Experiment in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\!Unstable Experiment in 5.mp3]]) 
LSM:Register("sound", "!Valk'yrs", [[Interface\Addons\SharedMedia_MyMedia\sound\!Valk'yrs.mp3]]) 
LSM:Register("sound", "!Volley Soon", [[Interface\Addons\SharedMedia_MyMedia\sound\!Volley Soon.mp3]]) 
LSM:Register("sound", "!Watch your Feet", [[Interface\Addons\SharedMedia_MyMedia\sound\!Watch your Feet.mp3]]) 
LSM:Register("sound", "Agility of the Vrykul", [[Interface\Addons\SharedMedia_MyMedia\sound\Agility of the Vrykul.mp3]]) 
LSM:Register("sound", "Aim of the Iron Dwarves", [[Interface\Addons\SharedMedia_MyMedia\sound\Aim of the Iron Dwarves.mp3]]) 
LSM:Register("sound", "Aura Mastery", [[Interface\Addons\SharedMedia_MyMedia\sound\Aura Mastery.mp3]]) 
LSM:Register("sound", "Beacon on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Beacon on You.mp3]]) 
LSM:Register("sound", "Beacon", [[Interface\Addons\SharedMedia_MyMedia\sound\Beacon.mp3]]) 
LSM:Register("sound", "Big Bang", [[Interface\Addons\SharedMedia_MyMedia\sound\Big Bang.mp3]]) 
LSM:Register("sound", "Bite", [[Interface\Addons\SharedMedia_MyMedia\sound\Bite.mp3]]) 
LSM:Register("sound", "Blistering Cold in", [[Interface\Addons\SharedMedia_MyMedia\sound\Blistering Cold in.mp3]]) 
LSM:Register("sound", "Blood Beasts in", [[Interface\Addons\SharedMedia_MyMedia\sound\Blood Beasts in.mp3]]) 
LSM:Register("sound", "Bloodlust - New", [[Interface\Addons\SharedMedia_MyMedia\sound\Bloodlust - New.mp3]]) 
LSM:Register("sound", "Bloodlust", [[Interface\Addons\SharedMedia_MyMedia\sound\Bloodlust.mp3]]) 
LSM:Register("sound", "Bone Spike", [[Interface\Addons\SharedMedia_MyMedia\sound\Bone Spike.mp3]]) 
LSM:Register("sound", "Bone Storm", [[Interface\Addons\SharedMedia_MyMedia\sound\Bone Storm.mp3]]) 
LSM:Register("sound", "Burning Bile on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Burning Bile on You.mp3]]) 
LSM:Register("sound", "Camp", [[Interface\Addons\SharedMedia_MyMedia\sound\Camp.mp3]]) 
LSM:Register("sound", "Choking in", [[Interface\Addons\SharedMedia_MyMedia\sound\Choking in.mp3]]) 
LSM:Register("sound", "Choking", [[Interface\Addons\SharedMedia_MyMedia\sound\Choking.mp3]]) 
LSM:Register("sound", "Cosmic Smash", [[Interface\Addons\SharedMedia_MyMedia\sound\Cosmic Smash.mp3]]) 
LSM:Register("sound", "Curse on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Curse on You.mp3]]) 
LSM:Register("sound", "Cutter in 3", [[Interface\Addons\SharedMedia_MyMedia\sound\Cutter in 3.mp3]]) 
LSM:Register("sound", "DBM Pull in", [[Interface\Addons\SharedMedia_MyMedia\sound\DBM Pull in.mp3]]) 
LSM:Register("sound", "DBM Pull", [[Interface\Addons\SharedMedia_MyMedia\sound\DBM Pull.mp3]]) 
LSM:Register("sound", "Defensives", [[Interface\Addons\SharedMedia_MyMedia\sound\Defensives.mp3]]) 
LSM:Register("sound", "Defile in", [[Interface\Addons\SharedMedia_MyMedia\sound\Defile in.mp3]]) 
LSM:Register("sound", "Defile near You", [[Interface\Addons\SharedMedia_MyMedia\sound\Defile near You.mp3]]) 
LSM:Register("sound", "Dispell Boss", [[Interface\Addons\SharedMedia_MyMedia\sound\Dispell Boss.mp3]]) 
LSM:Register("sound", "Dispell", [[Interface\Addons\SharedMedia_MyMedia\sound\Dispell.mp3]]) 
LSM:Register("sound", "Divine Hymn", [[Interface\Addons\SharedMedia_MyMedia\sound\Divine Hymn.mp3]]) 
LSM:Register("sound", "Divine Sacrifice", [[Interface\Addons\SharedMedia_MyMedia\sound\Divine Sacrifice.mp3]]) 
LSM:Register("sound", "Dominate Mind in", [[Interface\Addons\SharedMedia_MyMedia\sound\Dominate Mind in.mp3]]) 
LSM:Register("sound", "Dominate Mind", [[Interface\Addons\SharedMedia_MyMedia\sound\Dominate Mind.mp3]]) 
LSM:Register("sound", "Don't Release", [[Interface\Addons\SharedMedia_MyMedia\sound\Don't Release.mp3]]) 
LSM:Register("sound", "DPS hard", [[Interface\Addons\SharedMedia_MyMedia\sound\DPS hard.mp3]]) 
LSM:Register("sound", "DPS more", [[Interface\Addons\SharedMedia_MyMedia\sound\DPS more.mp3]]) 
LSM:Register("sound", "DPS slow", [[Interface\Addons\SharedMedia_MyMedia\sound\DPS slow.mp3]]) 
LSM:Register("sound", "DPS Stop", [[Interface\Addons\SharedMedia_MyMedia\sound\DPS Stop.mp3]]) 
LSM:Register("sound", "DPS", [[Interface\Addons\SharedMedia_MyMedia\sound\DPS.mp3]]) 
LSM:Register("sound", "Empowered Flame Orb on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Empowered Flame Orb on You.mp3]]) 
LSM:Register("sound", "Fear in", [[Interface\Addons\SharedMedia_MyMedia\sound\Fear in.mp3]]) 
LSM:Register("sound", "Fear", [[Interface\Addons\SharedMedia_MyMedia\sound\Fear.mp3]]) 
LSM:Register("sound", "Fiery Consumption on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Fiery Consumption on You.mp3]]) 
LSM:Register("sound", "Frostbolt Volley soon", [[Interface\Addons\SharedMedia_MyMedia\sound\Frostbolt Volley soon.mp3]]) 
LSM:Register("sound", "Gas Spore on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Gas Spore on You.mp3]]) 
LSM:Register("sound", "Glowing Twilight Scale", [[Interface\Addons\SharedMedia_MyMedia\sound\Glowing Twilight Scale.mp3]]) 
LSM:Register("sound", "Green Ooze", [[Interface\Addons\SharedMedia_MyMedia\sound\Green Ooze.mp3]]) 
LSM:Register("sound", "Grip", [[Interface\Addons\SharedMedia_MyMedia\sound\Grip.mp3]]) 
LSM:Register("sound", "Group Up", [[Interface\Addons\SharedMedia_MyMedia\sound\Group Up.mp3]]) 
LSM:Register("sound", "Guardian Spirit", [[Interface\Addons\SharedMedia_MyMedia\sound\Guardian Spirit.mp3]]) 
LSM:Register("sound", "Hand of Freedom", [[Interface\Addons\SharedMedia_MyMedia\sound\Hand of Freedom.mp3]]) 
LSM:Register("sound", "Hand of Protection", [[Interface\Addons\SharedMedia_MyMedia\sound\Hand of Protection.mp3]]) 
LSM:Register("sound", "Hand of Sacrifice cast", [[Interface\Addons\SharedMedia_MyMedia\sound\Hand of Sacrifice cast.mp3]]) 
LSM:Register("sound", "Hand of Sacrifice", [[Interface\Addons\SharedMedia_MyMedia\sound\Hand of Sacrifice.mp3]]) 
LSM:Register("sound", "Hand of Salvation", [[Interface\Addons\SharedMedia_MyMedia\sound\Hand of Salvation.mp3]]) 
LSM:Register("sound", "Hymn of Hope", [[Interface\Addons\SharedMedia_MyMedia\sound\Hymn of Hope.mp3]]) 
LSM:Register("sound", "Idiot", [[Interface\Addons\SharedMedia_MyMedia\sound\Idiot.mp3]]) 
LSM:Register("sound", "Incinerate Flesh on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Incinerate Flesh on You.mp3]]) 
LSM:Register("sound", "Infection on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Infection on You.mp3]]) 
LSM:Register("sound", "Infernal Erruption in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\Infernal Erruption in 5.mp3]]) 
LSM:Register("sound", "Infest cast", [[Interface\Addons\SharedMedia_MyMedia\sound\Infest cast.mp3]]) 
LSM:Register("sound", "Innervate", [[Interface\Addons\SharedMedia_MyMedia\sound\Innervate.mp3]]) 
LSM:Register("sound", "Interrupt", [[Interface\Addons\SharedMedia_MyMedia\sound\Interrupt.mp3]]) 
LSM:Register("sound", "Iphone", [[Interface\Addons\SharedMedia_MyMedia\sound\Iphone.mp3]]) 
LSM:Register("sound", "Laser Barrage", [[Interface\Addons\SharedMedia_MyMedia\sound\Laser Barrage.mp3]]) 
LSM:Register("sound", "Legion Flame on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Legion Flame on You.mp3]]) 
LSM:Register("sound", "Loot", [[Interface\Addons\SharedMedia_MyMedia\sound\Loot.mp3]]) 
LSM:Register("sound", "Malleable Goo in", [[Interface\Addons\SharedMedia_MyMedia\sound\Malleable Goo in.mp3]]) 
LSM:Register("sound", "Malleable Goo", [[Interface\Addons\SharedMedia_MyMedia\sound\Malleable Goo.mp3]]) 
LSM:Register("sound", "Mana Tide", [[Interface\Addons\SharedMedia_MyMedia\sound\Mana Tide.mp3]]) 
LSM:Register("sound", "Mark on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Mark on You.mp3]]) 
LSM:Register("sound", "Meteorstrike in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\Meteorstrike in 5.mp3]]) 
LSM:Register("sound", "Mindcontroll", [[Interface\Addons\SharedMedia_MyMedia\sound\Mindcontroll.mp3]]) 
LSM:Register("sound", "Mines", [[Interface\Addons\SharedMedia_MyMedia\sound\Mines.mp3]]) 
LSM:Register("sound", "Move Boss", [[Interface\Addons\SharedMedia_MyMedia\sound\Move Boss.mp3]]) 
LSM:Register("sound", "Move out", [[Interface\Addons\SharedMedia_MyMedia\sound\Move out.mp3]]) 
LSM:Register("sound", "Move", [[Interface\Addons\SharedMedia_MyMedia\sound\Move.mp3]]) 
LSM:Register("sound", "Necrotic Plague on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Necrotic Plague on You.mp3]]) 
LSM:Register("sound", "Nether Portal in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\Nether Portal in 5.mp3]]) 
LSM:Register("sound", "Pain Suppression", [[Interface\Addons\SharedMedia_MyMedia\sound\Pain Suppression.mp3]]) 
LSM:Register("sound", "Penetrating Cold on you", [[Interface\Addons\SharedMedia_MyMedia\sound\Penetrating Cold on you.mp3]]) 
LSM:Register("sound", "Piercing Twilight", [[Interface\Addons\SharedMedia_MyMedia\sound\Piercing Twilight.mp3]]) 
LSM:Register("sound", "Power of the Taunka", [[Interface\Addons\SharedMedia_MyMedia\sound\Power of the Taunka.mp3]]) 
LSM:Register("sound", "Precision of the iron Dwarves", [[Interface\Addons\SharedMedia_MyMedia\sound\Precision of the iron Dwarves.mp3]]) 
LSM:Register("sound", "PrePotion", [[Interface\Addons\SharedMedia_MyMedia\sound\PrePotion.mp3]]) 
LSM:Register("sound", "Pursued", [[Interface\Addons\SharedMedia_MyMedia\sound\Pursued.mp3]]) 
LSM:Register("sound", "Red ooze", [[Interface\Addons\SharedMedia_MyMedia\sound\Red ooze.mp3]]) 
LSM:Register("sound", "Save", [[Interface\Addons\SharedMedia_MyMedia\sound\Save.mp3]]) 
LSM:Register("sound", "Shadowtrap in", [[Interface\Addons\SharedMedia_MyMedia\sound\Shadowtrap in.mp3]]) 
LSM:Register("sound", "Shadowtrap near You", [[Interface\Addons\SharedMedia_MyMedia\sound\Shadowtrap near You.mp3]]) 
LSM:Register("sound", "Shadowtrap on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Shadowtrap on You.mp3]]) 
LSM:Register("sound", "Siphoned Power", [[Interface\Addons\SharedMedia_MyMedia\sound\Siphoned Power.mp3]]) 
LSM:Register("sound", "Slowed", [[Interface\Addons\SharedMedia_MyMedia\sound\Slowed.mp3]]) 
LSM:Register("sound", "Snobold Vassel on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Snobold Vassel on You.mp3]]) 
LSM:Register("sound", "SoftEnrage", [[Interface\Addons\SharedMedia_MyMedia\sound\SoftEnrage.mp3]]) 
LSM:Register("sound", "Soul Consumption on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Soul Consumption on You.mp3]]) 
LSM:Register("sound", "Special Ability", [[Interface\Addons\SharedMedia_MyMedia\sound\Special Ability.mp3]]) 
LSM:Register("sound", "Special in 5", [[Interface\Addons\SharedMedia_MyMedia\sound\Special in 5.mp3]]) 
LSM:Register("sound", "Speed of the Vrykul", [[Interface\Addons\SharedMedia_MyMedia\sound\Speed of the Vrykul.mp3]]) 
LSM:Register("sound", "Spirit Link on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Spirit Link on You.mp3]]) 
LSM:Register("sound", "Spirit on You - Run", [[Interface\Addons\SharedMedia_MyMedia\sound\Spirit on You - Run.mp3]]) 
LSM:Register("sound", "Spirits in", [[Interface\Addons\SharedMedia_MyMedia\sound\Spirits in.mp3]]) 
LSM:Register("sound", "Spirits", [[Interface\Addons\SharedMedia_MyMedia\sound\Spirits.mp3]]) 
LSM:Register("sound", "Stacks high", [[Interface\Addons\SharedMedia_MyMedia\sound\Stacks high.mp3]]) 
LSM:Register("sound", "Stop Casting", [[Interface\Addons\SharedMedia_MyMedia\sound\Stop Casting.mp3]]) 
LSM:Register("sound", "Strength of the Taunka", [[Interface\Addons\SharedMedia_MyMedia\sound\Strength of the Taunka.mp3]]) 
LSM:Register("sound", "Stunned", [[Interface\Addons\SharedMedia_MyMedia\sound\Stunned.mp3]]) 
LSM:Register("sound", "Suppressors in", [[Interface\Addons\SharedMedia_MyMedia\sound\Suppressors in.mp3]]) 
LSM:Register("sound", "Swarming Shadows on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Swarming Shadows on You.mp3]]) 
LSM:Register("sound", "Switch Tank", [[Interface\Addons\SharedMedia_MyMedia\sound\Switch Tank.mp3]]) 
LSM:Register("sound", "Switch Target", [[Interface\Addons\SharedMedia_MyMedia\sound\Switch Target.mp3]]) 
LSM:Register("sound", "Toxin on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Toxin on You.mp3]]) 
LSM:Register("sound", "Tranquilizing Shot now", [[Interface\Addons\SharedMedia_MyMedia\sound\Tranquilizing Shot now.mp3]]) 
LSM:Register("sound", "Tricks Now", [[Interface\Addons\SharedMedia_MyMedia\sound\Tricks Now.mp3]]) 
LSM:Register("sound", "Twilight Flames", [[Interface\Addons\SharedMedia_MyMedia\sound\Twilight Flames.mp3]]) 
LSM:Register("sound", "Unbound Plague on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Unbound Plague on You.mp3]]) 
LSM:Register("sound", "Unchained on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Unchained on You.mp3]]) 
LSM:Register("sound", "Unstable Experiment", [[Interface\Addons\SharedMedia_MyMedia\sound\Unstable Experiment.mp3]]) 
LSM:Register("sound", "Valk'yrs", [[Interface\Addons\SharedMedia_MyMedia\sound\Valk'yrs.mp3]]) 
LSM:Register("sound", "Vile Gas on You", [[Interface\Addons\SharedMedia_MyMedia\sound\Vile Gas on You.mp3]]) 
LSM:Register("sound", "Watch Aggro", [[Interface\Addons\SharedMedia_MyMedia\sound\Watch Aggro.mp3]]) 
LSM:Register("sound", "Watch Position", [[Interface\Addons\SharedMedia_MyMedia\sound\Watch Position.mp3]]) 
LSM:Register("sound", "Wrong Target", [[Interface\Addons\SharedMedia_MyMedia\sound\Wrong Target.mp3]]) 

-- -----
--   STATUSBAR
-- -----
LSM:Register("statusbar", "Aluminium", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Aluminium.tga]]) 
LSM:Register("statusbar", "Armory", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Armory.tga]]) 
LSM:Register("statusbar", "BantoBar", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BantoBar.tga]]) 
LSM:Register("statusbar", "Bars", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Bars.tga]]) 
LSM:Register("statusbar", "Bezo-dark1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Bezo-dark1.blp]]) 
LSM:Register("statusbar", "Bezo-dark2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Bezo-dark2.blp]]) 
LSM:Register("statusbar", "Bezo", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Bezo.blp]]) 
LSM:Register("statusbar", "Blinkii", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Blinkii.tga]]) 
LSM:Register("statusbar", "BuiOnePixel", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BuiOnePixel.tga]]) 
LSM:Register("statusbar", "Bumps", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Bumps.tga]]) 
LSM:Register("statusbar", "Button", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Button.tga]]) 
LSM:Register("statusbar", "Charcoal", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Charcoal.tga]]) 
LSM:Register("statusbar", "Cilo", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Cilo.tga]]) 
LSM:Register("statusbar", "Cloud", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Cloud.tga]]) 
LSM:Register("statusbar", "Combo", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Combo.tga]]) 
LSM:Register("statusbar", "Comet", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Comet.tga]]) 
LSM:Register("statusbar", "Dabs", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Dabs.tga]]) 
LSM:Register("statusbar", "DarkBottom", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DarkBottom.tga]]) 
LSM:Register("statusbar", "Diagonal", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Diagonal.tga]]) 
LSM:Register("statusbar", "Empty", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Empty.tga]]) 
LSM:Register("statusbar", "Falumn", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Falumn.tga]]) 
LSM:Register("statusbar", "Ferous1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous1.tga]]) 
LSM:Register("statusbar", "Ferous10", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous10.tga]]) 
LSM:Register("statusbar", "Ferous11", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous11.tga]]) 
LSM:Register("statusbar", "Ferous12", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous12.tga]]) 
LSM:Register("statusbar", "Ferous13", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous13.tga]]) 
LSM:Register("statusbar", "Ferous14", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous14.tga]]) 
LSM:Register("statusbar", "Ferous15", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous15.tga]]) 
LSM:Register("statusbar", "Ferous16", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous16.tga]]) 
LSM:Register("statusbar", "Ferous17", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous17.tga]]) 
LSM:Register("statusbar", "Ferous18", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous18.tga]]) 
LSM:Register("statusbar", "Ferous19", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous19.tga]]) 
LSM:Register("statusbar", "Ferous2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous2.tga]]) 
LSM:Register("statusbar", "Ferous20", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous20.tga]]) 
LSM:Register("statusbar", "Ferous21", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous21.tga]]) 
LSM:Register("statusbar", "Ferous22", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous22.tga]]) 
LSM:Register("statusbar", "Ferous23", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous23.tga]]) 
LSM:Register("statusbar", "Ferous24", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous24.tga]]) 
LSM:Register("statusbar", "Ferous25", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous25.tga]]) 
LSM:Register("statusbar", "Ferous26", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous26.tga]]) 
LSM:Register("statusbar", "Ferous27", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous27.tga]]) 
LSM:Register("statusbar", "Ferous28", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous28.tga]]) 
LSM:Register("statusbar", "Ferous29", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous29.tga]]) 
LSM:Register("statusbar", "Ferous3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous3.tga]]) 
LSM:Register("statusbar", "Ferous30", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous30.tga]]) 
LSM:Register("statusbar", "Ferous31", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous31.tga]]) 
LSM:Register("statusbar", "Ferous32", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous32.tga]]) 
LSM:Register("statusbar", "Ferous33", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous33.tga]]) 
LSM:Register("statusbar", "Ferous34", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous34.tga]]) 
LSM:Register("statusbar", "Ferous35", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous35.tga]]) 
LSM:Register("statusbar", "Ferous36", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous36.tga]]) 
LSM:Register("statusbar", "Ferous37", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous37.tga]]) 
LSM:Register("statusbar", "Ferous4", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous4.tga]]) 
LSM:Register("statusbar", "Ferous5", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous5.tga]]) 
LSM:Register("statusbar", "Ferous6", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous6.tga]]) 
LSM:Register("statusbar", "Ferous7", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous7.tga]]) 
LSM:Register("statusbar", "Ferous8", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous8.tga]]) 
LSM:Register("statusbar", "Ferous9", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ferous9.tga]]) 
LSM:Register("statusbar", "Fifths", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Fifths.tga]]) 
LSM:Register("statusbar", "Flat", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Flat.tga]]) 
LSM:Register("statusbar", "Fourths", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Fourths.tga]]) 
LSM:Register("statusbar", "Frost", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Frost.tga]]) 
LSM:Register("statusbar", "Glamour", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour.tga]]) 
LSM:Register("statusbar", "Glamour2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour2.tga]]) 
LSM:Register("statusbar", "Glamour3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour3.tga]]) 
LSM:Register("statusbar", "Glamour4", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour4.tga]]) 
LSM:Register("statusbar", "Glamour5", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour5.tga]]) 
LSM:Register("statusbar", "Glamour6", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour6.tga]]) 
LSM:Register("statusbar", "Glamour7", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour7.tga]]) 
LSM:Register("statusbar", "Glass", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glass.tga]]) 
LSM:Register("statusbar", "Glaze", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glaze.tga]]) 
LSM:Register("statusbar", "Glaze2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glaze2.tga]]) 
LSM:Register("statusbar", "Gloss", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Gloss.tga]]) 
LSM:Register("statusbar", "glowTex", [[Interface\Addons\SharedMedia_MyMedia\statusbar\glowTex.tga]]) 
LSM:Register("statusbar", "Graphite", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Graphite.tga]]) 
LSM:Register("statusbar", "Grid", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Grid.tga]]) 
LSM:Register("statusbar", "Hatched", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Hatched.tga]]) 
LSM:Register("statusbar", "Healbot", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Healbot.tga]]) 
LSM:Register("statusbar", "LiteStep", [[Interface\Addons\SharedMedia_MyMedia\statusbar\LiteStep.tga]]) 
LSM:Register("statusbar", "LiteStepLite", [[Interface\Addons\SharedMedia_MyMedia\statusbar\LiteStepLite.tga]]) 
LSM:Register("statusbar", "Lyfe", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Lyfe.tga]]) 
LSM:Register("statusbar", "Melli", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Melli.tga]]) 
LSM:Register("statusbar", "MelliDark", [[Interface\Addons\SharedMedia_MyMedia\statusbar\MelliDark.tga]]) 
LSM:Register("statusbar", "MelliDarkRough", [[Interface\Addons\SharedMedia_MyMedia\statusbar\MelliDarkRough.tga]]) 
LSM:Register("statusbar", "Minimalist", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Minimalist.tga]]) 
LSM:Register("statusbar", "Norm", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Norm.tga]]) 
LSM:Register("statusbar", "normTex", [[Interface\Addons\SharedMedia_MyMedia\statusbar\normTex.tga]]) 
LSM:Register("statusbar", "normTex2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\normTex2.tga]]) 
LSM:Register("statusbar", "Otravi", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Otravi.tga]]) 
LSM:Register("statusbar", "Outline", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Outline.tga]]) 
LSM:Register("statusbar", "Perl", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Perl.tga]]) 
LSM:Register("statusbar", "Perl2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Perl2.tga]]) 
LSM:Register("statusbar", "Pill", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Pill.tga]]) 
LSM:Register("statusbar", "Raeli1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Raeli1.tga]]) 
LSM:Register("statusbar", "Raeli2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Raeli2.tga]]) 
LSM:Register("statusbar", "Raeli3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Raeli3.tga]]) 
LSM:Register("statusbar", "Raeli4", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Raeli4.tga]]) 
LSM:Register("statusbar", "Raeli5", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Raeli5.tga]]) 
LSM:Register("statusbar", "Raeli6", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Raeli6.tga]]) 
LSM:Register("statusbar", "Rain", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Rain.tga]]) 
LSM:Register("statusbar", "Rocks", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Rocks.tga]]) 
LSM:Register("statusbar", "Round", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Round.tga]]) 
LSM:Register("statusbar", "Ruben", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ruben.tga]]) 
LSM:Register("statusbar", "Runes", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Runes.tga]]) 
LSM:Register("statusbar", "Skewed", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Skewed.tga]]) 
LSM:Register("statusbar", "Smooth", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Smooth.tga]]) 
LSM:Register("statusbar", "Smoothv2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Smoothv2.tga]]) 
LSM:Register("statusbar", "Smudge", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Smudge.tga]]) 
LSM:Register("statusbar", "Steel", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Steel.tga]]) 
LSM:Register("statusbar", "Striped", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Striped.tga]]) 
LSM:Register("statusbar", "Threatbar", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Threatbar.tga]]) 
LSM:Register("statusbar", "ToxiUI-clean", [[Interface\Addons\SharedMedia_MyMedia\statusbar\ToxiUI-clean.tga]]) 
LSM:Register("statusbar", "ToxiUI-dark", [[Interface\Addons\SharedMedia_MyMedia\statusbar\ToxiUI-dark.tga]]) 
LSM:Register("statusbar", "ToxiUI-g1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\ToxiUI-g1.tga]]) 
LSM:Register("statusbar", "ToxiUI-g2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\ToxiUI-g2.tga]]) 
LSM:Register("statusbar", "ToxiUI-grad", [[Interface\Addons\SharedMedia_MyMedia\statusbar\ToxiUI-grad.tga]]) 
LSM:Register("statusbar", "ToxiUI-half", [[Interface\Addons\SharedMedia_MyMedia\statusbar\ToxiUI-half.tga]]) 
LSM:Register("statusbar", "Tube", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Tube.tga]]) 
LSM:Register("statusbar", "TX-WorldState-Score", [[Interface\Addons\SharedMedia_MyMedia\statusbar\TX-WorldState-Score.blp]]) 
LSM:Register("statusbar", "VargothUI", [[Interface\Addons\SharedMedia_MyMedia\statusbar\VargothUI.tga]]) 
LSM:Register("statusbar", "VargothUI2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\VargothUI2.tga]]) 
LSM:Register("statusbar", "VargothUI2Border", [[Interface\Addons\SharedMedia_MyMedia\statusbar\VargothUI2Border.tga]]) 
LSM:Register("statusbar", "Water", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Water.tga]]) 
LSM:Register("statusbar", "Wglass", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Wglass.tga]]) 
LSM:Register("statusbar", "Wisps", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Wisps.tga]]) 
LSM:Register("statusbar", "Xeon", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Xeon.tga]]) 
